/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package java5774_1248_0915_gui;

import MyPackages.Policy;
import MyPackages.Policy.InsrncCmpny;
import MyPackages.Policy.PlicyType;
import DataAccessObject.IBackend_DAO_List_impl;
import DataAccessObject.Singelton;
import java.awt.Toolkit;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JTable;

/**
 *
 * @author dell
 */
public class JustViewPolicyForm extends javax.swing.JFrame {
    private static final long serialVersionUID = 1L;

    /**
     * Creates new form AddPolicy
     */
    private long per_id;
    private long policy_id;
    
    private Policy policy=null; 
    private static IBackend_DAO_List_impl sngltn = null;
    static {
                try 
                {
                sngltn=Singelton.getMySingelton();
                } 
                catch (Exception ex) 
                {
                    Logger.getLogger(AddCstmrCrdForm.class.getName()).log(Level.SEVERE, null, ex);
                }
            };
    public JustViewPolicyForm(long PerId,Object PolicyID) throws Exception {
        per_id=PerId;
        policy_id=Long.valueOf(PolicyID.toString());
        
        policy =new Policy();
        policy=sngltn.GetPolicyById(policy_id);
        
        int NumOfDetails=policy.getMoreDetails().size();
        
        initComponents();
        java.awt.event.WindowEvent MyWindow = null;
        formWindowOpened(MyWindow);
        
        ComboBoxPolictType.setModel(new DefaultComboBoxModel(PlicyType.values()));
        ComboBoxInsuranceCompany.setModel(new DefaultComboBoxModel(InsrncCmpny.values()));
        
        DetailsFieldsFirstDesplay(NumOfDetails);
        
        TextPerson_Name_ID.setEnabled(false);
        TextPerson_Name_ID.setText("Person Name: "+ 
                                    sngltn.GetMyPersonCstmrCrd(per_id).getPer().getPerName() + "\n"+
                                    "Preson ID: "+
                                    Long.toString(per_id)
                                    );
        EnterRepresentativeName.setText(policy.getRepresentativeName());
        jSpinnerPolicyId.setValue(policy_id);
        ComboBoxPolictType.setSelectedItem(policy.getPolicyType());
        ComboBoxInsuranceCompany.setSelectedItem(policy.getInsuranceCompany());
        jSpinnerOpeningDate.setValue(policy.getOpeningDate());
        jSpinnerPolicyRate.setValue(policy.getPolicyRate());
        if (NumOfDetails==1)
            EnterDetail0.setText(policy.getMoreDetails().get(0));
        else if (NumOfDetails==2)
                                {
                                    EnterDetail0.setText(policy.getMoreDetails().get(0));
                                    EnterDetail1.setText(policy.getMoreDetails().get(1));
                                }
        else if (NumOfDetails==3)
                                {
                                    EnterDetail0.setText(policy.getMoreDetails().get(0));
                                    EnterDetail1.setText(policy.getMoreDetails().get(1));
                                    EnterDetail2.setText(policy.getMoreDetails().get(2));
                                }
         else if (NumOfDetails==4)
                                {
                                    EnterDetail0.setText(policy.getMoreDetails().get(0));
                                    EnterDetail1.setText(policy.getMoreDetails().get(1));
                                    EnterDetail2.setText(policy.getMoreDetails().get(2));
                                    EnterDetail3.setText(policy.getMoreDetails().get(3));
                                }
       
    }

    private JustViewPolicyForm() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    
     private void formWindowOpened(java.awt.event.WindowEvent evt) {                                  
        int lebar = this.getWidth()/2;
        int tinggi = this.getHeight()/2;
        int x = (Toolkit.getDefaultToolkit().getScreenSize().width/2)-lebar;
        int y = (Toolkit.getDefaultToolkit().getScreenSize().height/2)-tinggi;
        this.setLocation(x, y);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        EnterRepresentativeName = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jSpinnerOpeningDate = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        EnterDetail0 = new java.awt.TextField();
        EnterDetail2 = new java.awt.TextField();
        EnterDetail3 = new java.awt.TextField();
        EnterDetail1 = new java.awt.TextField();
        jSpinnerPolicyId = new javax.swing.JSpinner();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        ComboBoxPolictType = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        ComboBoxInsuranceCompany = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jSpinnerPolicyRate = new javax.swing.JSpinner();
        jScrollPane1 = new javax.swing.JScrollPane();
        TextPerson_Name_ID = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        EnterRepresentativeName.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        EnterRepresentativeName.setText("Enter Representative Name");
        EnterRepresentativeName.setEnabled(false);
        getContentPane().add(EnterRepresentativeName, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 170, 30));

        jLabel1.setText("Representative Name:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 130, 30));

        jSpinnerOpeningDate.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jSpinnerOpeningDate.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(), null, null, java.util.Calendar.DAY_OF_YEAR));
        jSpinnerOpeningDate.setEnabled(false);
        getContentPane().add(jSpinnerOpeningDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 230, 165, -1));

        jLabel2.setText("Opening Date:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 106, -1));

        jLabel3.setText("More Details:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, -1, -1));

        EnterDetail0.setEnabled(false);
        EnterDetail0.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        EnterDetail0.setMaximumSize(new java.awt.Dimension(72, 21));
        EnterDetail0.setText("Enter Detail");
        EnterDetail0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnterDetail0ActionPerformed(evt);
            }
        });
        getContentPane().add(EnterDetail0, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, 339, -1));

        EnterDetail2.setEnabled(false);
        EnterDetail2.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        EnterDetail2.setMaximumSize(new java.awt.Dimension(72, 21));
        EnterDetail2.setText("Enter Detail");
        getContentPane().add(EnterDetail2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 420, 339, -1));

        EnterDetail3.setEnabled(false);
        EnterDetail3.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        EnterDetail3.setMaximumSize(new java.awt.Dimension(72, 21));
        EnterDetail3.setText("Enter Detail");
        getContentPane().add(EnterDetail3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 460, 339, -1));

        EnterDetail1.setEnabled(false);
        EnterDetail1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        EnterDetail1.setMaximumSize(new java.awt.Dimension(72, 21));
        EnterDetail1.setText("Enter Detail");
        EnterDetail1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnterDetail1ActionPerformed(evt);
            }
        });
        getContentPane().add(EnterDetail1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, 339, -1));

        jSpinnerPolicyId.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jSpinnerPolicyId.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jSpinnerPolicyId.setEnabled(false);
        getContentPane().add(jSpinnerPolicyId, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, 78, -1));

        jLabel4.setText("Policy ID:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        jLabel5.setText("* predetermined");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 110, -1, -1));

        ComboBoxPolictType.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        ComboBoxPolictType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        ComboBoxPolictType.setEnabled(false);
        getContentPane().add(ComboBoxPolictType, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, 165, -1));

        jLabel6.setText("Policy Type:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, -1));

        ComboBoxInsuranceCompany.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        ComboBoxInsuranceCompany.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        ComboBoxInsuranceCompany.setEnabled(false);
        getContentPane().add(ComboBoxInsuranceCompany, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 190, 165, -1));

        jLabel7.setText("Insurance Company:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, -1));

        jLabel8.setText("Policy Rate:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 83, -1));

        jSpinnerPolicyRate.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jSpinnerPolicyRate.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(0), Integer.valueOf(0), null, Integer.valueOf(1)));
        jSpinnerPolicyRate.setEnabled(false);
        getContentPane().add(jSpinnerPolicyRate, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 270, 98, -1));

        TextPerson_Name_ID.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jScrollPane1.setViewportView(TextPerson_Name_ID);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 322, 54));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EnterDetail0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnterDetail0ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EnterDetail0ActionPerformed

    private void EnterDetail1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnterDetail1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EnterDetail1ActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
                                    
    }//GEN-LAST:event_formWindowClosed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing

    }//GEN-LAST:event_formWindowClosing
                  
        private void DetailsFieldsFirstDesplay(int list_lentgh)
        {
            if (list_lentgh==1)
                          {
                            EnterDetail0.setVisible(true);
                            EnterDetail1.setVisible(false);
                            EnterDetail2.setVisible(false);
                            EnterDetail3.setVisible(false);
                            this.setSize(430, 405);
                          }
        else if (list_lentgh==2)
                                {
                                  EnterDetail0.setVisible(true);
                                  EnterDetail1.setVisible(true);
                                  this.setSize(430, 445);
                                }
        
        else if (list_lentgh==3)
                                {
                                EnterDetail0.setVisible(true);
                                EnterDetail1.setVisible(true);
                                EnterDetail2.setVisible(true);
                                this.setSize(430, 485);
                                }
        else if (list_lentgh==4)
                                {
                                 EnterDetail0.setVisible(true);
                                 EnterDetail1.setVisible(true);
                                 EnterDetail2.setVisible(true);
                                 EnterDetail3.setVisible(true);  
                                 this.setSize(430, 520);
                                }
        
        }
        
        
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JustViewPolicyForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JustViewPolicyForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JustViewPolicyForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JustViewPolicyForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JustViewPolicyForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox ComboBoxInsuranceCompany;
    private javax.swing.JComboBox ComboBoxPolictType;
    private java.awt.TextField EnterDetail0;
    private java.awt.TextField EnterDetail1;
    private java.awt.TextField EnterDetail2;
    private java.awt.TextField EnterDetail3;
    private javax.swing.JTextField EnterRepresentativeName;
    private javax.swing.JTextPane TextPerson_Name_ID;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinnerOpeningDate;
    private javax.swing.JSpinner jSpinnerPolicyId;
    private javax.swing.JSpinner jSpinnerPolicyRate;
    // End of variables declaration//GEN-END:variables

    void show(JTable jTablePolicyView) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
