/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package java5774_1248_0915_gui;

import DataAccessObject.Controller;
import DataAccessObject.Singelton;
import java.awt.Toolkit;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import Packages.Claim;
import Packages.CustomerCrd;
import Packages.Policy;

/**
 * @author dell
 */
public class QueriesAndViewingDataForm extends javax.swing.JFrame {

    private static final long serialVersionUID = 1L;
    private final Runnable enableMainFormMyFunc;
    private static Controller sngltn = null;

    static {
        try {
            sngltn = Singelton.getMySingelton();
        } catch (Exception ex) {
            Logger.getLogger(AddCstmrCrdForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    // Ctor
    public QueriesAndViewingDataForm(Runnable myfunc) throws Exception {
        enableMainFormMyFunc = myfunc;
        initComponents();
        java.awt.event.WindowEvent MyWindow = null;
        formWindowOpened(MyWindow);

        ArrayList<Long> AllPersonsID = new ArrayList<Long>();
        for (CustomerCrd CstmrCrd : sngltn.GetAllCustemers()) {
            AllPersonsID.add(Long.valueOf(CstmrCrd.getPerson().getId()));
        }

        jComboBoxSelectPersonID.setModel(new DefaultComboBoxModel(AllPersonsID.toArray()));
        jComboBoxPolicyType.setModel(new DefaultComboBoxModel(Policy.PlicyType.values()));

        jComboBoxClaimStatus.setModel(new DefaultComboBoxModel(Claim.ClaimStat.values()));
        jComboBoxClaimEventType.setModel(new DefaultComboBoxModel(Claim.EvntType.values()));
    }

    // aligment the window
    private void formWindowOpened(java.awt.event.WindowEvent evt) {
        int lebar = this.getWidth() / 2;
        int tinggi = this.getHeight() / 2;
        int x = (Toolkit.getDefaultToolkit().getScreenSize().width / 2) - lebar;
        int y = (Toolkit.getDefaultToolkit().getScreenSize().height / 2) - tinggi;
        this.setLocation(x, y);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonViewAllClaims = new javax.swing.JButton();
        jButtonViewAllOpenClaims = new javax.swing.JButton();
        jButtonViewAllClaimWithThisStauts = new javax.swing.JButton();
        jButtonViewAllClaimWithThisEventType = new javax.swing.JButton();
        jButtonViewAllPolicies = new javax.swing.JButton();
        jButtonViewThisPersonCstmrCrd = new javax.swing.JButton();
        jButtonViewAllPoliciesWithThisPolicyType = new javax.swing.JButton();
        jComboBoxSelectPersonID = new javax.swing.JComboBox();
        jComboBoxPolicyType = new javax.swing.JComboBox();
        jComboBoxClaimStatus = new javax.swing.JComboBox();
        jComboBoxClaimEventType = new javax.swing.JComboBox();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 350));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonViewAllClaims.setText("View All Claims");
        jButtonViewAllClaims.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonViewAllClaimsActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonViewAllClaims, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 140, 230, -1));

        jButtonViewAllOpenClaims.setText("View All Open Claims");
        jButtonViewAllOpenClaims.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonViewAllOpenClaimsActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonViewAllOpenClaims, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 190, 230, -1));

        jButtonViewAllClaimWithThisStauts.setText("View all Claim with this stauts");
        jButtonViewAllClaimWithThisStauts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonViewAllClaimWithThisStautsActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonViewAllClaimWithThisStauts, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 240, 230, -1));

        jButtonViewAllClaimWithThisEventType.setText("View all Claim with this Event Type");
        jButtonViewAllClaimWithThisEventType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonViewAllClaimWithThisEventTypeActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonViewAllClaimWithThisEventType, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 290, 230, -1));

        jButtonViewAllPolicies.setText("View All Policies");
        jButtonViewAllPolicies.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonViewAllPoliciesActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonViewAllPolicies, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 140, 230, -1));

        jButtonViewThisPersonCstmrCrd.setText("View This Person CstmrCrd");
        jButtonViewThisPersonCstmrCrd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonViewThisPersonCstmrCrdActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonViewThisPersonCstmrCrd, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 60, 280, -1));

        jButtonViewAllPoliciesWithThisPolicyType.setText("View all Policies with this policy type");
        jButtonViewAllPoliciesWithThisPolicyType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonViewAllPoliciesWithThisPolicyTypeActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonViewAllPoliciesWithThisPolicyType, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, 230, -1));

        jComboBoxSelectPersonID.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jComboBoxSelectPersonID, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 30, 170, -1));

        jComboBoxPolicyType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxPolicyType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxPolicyTypeActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBoxPolicyType, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 120, -1));

        jComboBoxClaimStatus.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jComboBoxClaimStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 240, 80, -1));

        jComboBoxClaimEventType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jComboBoxClaimEventType, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 290, 80, -1));

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 120, 10, 230));

        jLabel1.setText("Select Person ID:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 30, 110, 20));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, 400, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // handle click for all exists claims
    private void jButtonViewAllClaimsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonViewAllClaimsActionPerformed
        try {
            if (sngltn.GetAllClaims().isEmpty()) {
                JOptionPane.showMessageDialog(null, "No information to display. \n"
                        + "Until this moment there is'nt any claim Activity in your database.", "", JOptionPane.PLAIN_MESSAGE);
            } else {
                ClaimsTableViewForm ViewClaimsTable = null;
                ViewClaimsTable = new ClaimsTableViewForm(jButtonViewAllClaims.getText());
                ViewClaimsTable.show();
            }
        } catch (Exception ex) {
            Logger.getLogger(QueriesAndViewingDataForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonViewAllClaimsActionPerformed

    private void jComboBoxPolicyTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxPolicyTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxPolicyTypeActionPerformed

    // handle click for all exists policies
    private void jButtonViewAllPoliciesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonViewAllPoliciesActionPerformed
        try {
            if (sngltn.GetAllPolicies().isEmpty()) {
                JOptionPane.showMessageDialog(null, "No information to display. \n"
                        + "Until this moment there is'nt any policy Activity in your database.", "", JOptionPane.PLAIN_MESSAGE);
            } else {
                PoliciesTableViewForm ViewPoliciesTable = null;
                ViewPoliciesTable = new PoliciesTableViewForm(jButtonViewAllPolicies.getText());
                ViewPoliciesTable.show();
            }
        } catch (Exception ex) {
            Logger.getLogger(QueriesAndViewingDataForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonViewAllPoliciesActionPerformed

    // handle click for all exists claims with specific event type
    private void jButtonViewAllClaimWithThisEventTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonViewAllClaimWithThisEventTypeActionPerformed
        ClaimsTableViewForm viewClaimsTable = null;
        boolean check = false;
        try {
            for (CustomerCrd ctmrCrd : sngltn.GetAllCustemers()) {
                if ((sngltn.GetMyEventClaims((Claim.EvntType) jComboBoxClaimEventType.getSelectedItem(), ctmrCrd.getPerson()).isEmpty()) == false) {
                    check = true;
                    break;
                }
            }
        } catch (Exception ex) {
            Logger.getLogger(QueriesAndViewingDataForm.class.getName()).log(Level.SEVERE, null, ex);
        }

        if (!check) {
            JOptionPane.showMessageDialog(null, "No information to display. \n"
                    + "Until this moment there is'nt Claim with this (" + jComboBoxClaimEventType.getSelectedItem().toString() + ") ClaimEventType in your database.", "", JOptionPane.PLAIN_MESSAGE);
        } else {
            try {
                viewClaimsTable = new ClaimsTableViewForm(jButtonViewAllClaimWithThisEventType.getText(), (Claim.EvntType) jComboBoxClaimEventType.getSelectedItem());
            } catch (Exception ex) {
                Logger.getLogger(QueriesAndViewingDataForm.class.getName()).log(Level.SEVERE, null, ex);
            }
            viewClaimsTable.show();
        }
    }//GEN-LAST:event_jButtonViewAllClaimWithThisEventTypeActionPerformed

    // closing the window
    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        enableMainFormMyFunc.run();
    }//GEN-LAST:event_formWindowClosing

    // handle click for view customer card of a person
    private void jButtonViewThisPersonCstmrCrdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonViewThisPersonCstmrCrdActionPerformed
        JustViewCstmrCrdForm JustViewCstmrCrd = null;
        try {
            JustViewCstmrCrd = new JustViewCstmrCrdForm(Long.valueOf(jComboBoxSelectPersonID.getSelectedItem().toString()));
        } catch (Exception ex) {
            Logger.getLogger(QueriesAndViewingDataForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        JustViewCstmrCrd.show();

    }//GEN-LAST:event_jButtonViewThisPersonCstmrCrdActionPerformed

    // handle click for all exists policies with specific policy type
    private void jButtonViewAllPoliciesWithThisPolicyTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonViewAllPoliciesWithThisPolicyTypeActionPerformed
        PoliciesTableViewForm ViewPoliciesTable = null;
        boolean check = false;
        try {
            for (CustomerCrd ctmrCrd : sngltn.GetAllCustemers()) {
                if ((sngltn.GetMyTypePolicies((Policy.PlicyType) jComboBoxPolicyType.getSelectedItem(), ctmrCrd.getPerson()).isEmpty()) == false) {
                    check = true;
                    break;
                }
            }
        } catch (Exception ex) {
            Logger.getLogger(QueriesAndViewingDataForm.class.getName()).log(Level.SEVERE, null, ex);
        }

        if (!check) {
            JOptionPane.showMessageDialog(null, "No information to display. \n"
                    + "Until this moment there is'nt policy with this (" + jComboBoxPolicyType.getSelectedItem().toString() + ") PolicyType in your database.", "", JOptionPane.PLAIN_MESSAGE);
        } else {
            try {
                ViewPoliciesTable = new PoliciesTableViewForm(jButtonViewAllPoliciesWithThisPolicyType.getText(), (Policy.PlicyType) jComboBoxPolicyType.getSelectedItem());
            } catch (Exception ex) {
                Logger.getLogger(QueriesAndViewingDataForm.class.getName()).log(Level.SEVERE, null, ex);
            }
            ViewPoliciesTable.show();
        }

    }//GEN-LAST:event_jButtonViewAllPoliciesWithThisPolicyTypeActionPerformed

    // handle click for view all claims that still open
    private void jButtonViewAllOpenClaimsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonViewAllOpenClaimsActionPerformed
        ClaimsTableViewForm viewClaimsTable = null;
        try {
            if (sngltn.GetAllOpenClaims().isEmpty()) {
                JOptionPane.showMessageDialog(null, "No information to display. \n"
                        + "As of this moment,all the claims are closed! (Confirmed or Deferred)", "", JOptionPane.PLAIN_MESSAGE);
            } else {
                try {
                    viewClaimsTable = new ClaimsTableViewForm(jButtonViewAllOpenClaims.getText());
                    viewClaimsTable.show();
                } catch (Exception ex) {
                    Logger.getLogger(QueriesAndViewingDataForm.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        } catch (Exception ex) {
            Logger.getLogger(QueriesAndViewingDataForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonViewAllOpenClaimsActionPerformed

    // handle click for all exists claims with specific status
    private void jButtonViewAllClaimWithThisStautsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonViewAllClaimWithThisStautsActionPerformed
        ClaimsTableViewForm viewClaimsTable = null;
        boolean check = false;
        try {
            for (CustomerCrd ctmrCrd : sngltn.GetAllCustemers()) {
                if ((sngltn.GetMyStatusClaims((Claim.ClaimStat) jComboBoxClaimStatus.getSelectedItem(), ctmrCrd.getPerson()).isEmpty()) == false) {
                    check = true;
                    break;
                }
            }
        } catch (Exception ex) {
            Logger.getLogger(QueriesAndViewingDataForm.class.getName()).log(Level.SEVERE, null, ex);
        }

        if (!check) {
            JOptionPane.showMessageDialog(null, "No information to display. \n"
                    + "Until this moment there is'nt Claim with this (" + jComboBoxClaimStatus.getSelectedItem().toString() + ") ClaimStatus in your database.", "", JOptionPane.PLAIN_MESSAGE);
        } else {
            try {
                viewClaimsTable = new ClaimsTableViewForm(jButtonViewAllClaimWithThisStauts.getText(), (Claim.ClaimStat) jComboBoxClaimStatus.getSelectedItem());
            } catch (Exception ex) {
                Logger.getLogger(QueriesAndViewingDataForm.class.getName()).log(Level.SEVERE, null, ex);
            }
            viewClaimsTable.show();
        }
    }//GEN-LAST:event_jButtonViewAllClaimWithThisStautsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QueriesAndViewingDataForm.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QueriesAndViewingDataForm.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QueriesAndViewingDataForm.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QueriesAndViewingDataForm.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    //  new QueriesAndViewingDataForm().setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(QueriesAndViewingDataForm.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonViewAllClaimWithThisEventType;
    private javax.swing.JButton jButtonViewAllClaimWithThisStauts;
    private javax.swing.JButton jButtonViewAllClaims;
    private javax.swing.JButton jButtonViewAllOpenClaims;
    private javax.swing.JButton jButtonViewAllPolicies;
    private javax.swing.JButton jButtonViewAllPoliciesWithThisPolicyType;
    private javax.swing.JButton jButtonViewThisPersonCstmrCrd;
    private javax.swing.JComboBox jComboBoxClaimEventType;
    private javax.swing.JComboBox jComboBoxClaimStatus;
    private javax.swing.JComboBox jComboBoxPolicyType;
    private javax.swing.JComboBox jComboBoxSelectPersonID;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration//GEN-END:variables

}
